"""Initial members table

Revision ID: c82bdf5a2995
Revises: 
Create Date: 2025-05-07 20:03:20.975897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c82bdf5a2995'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_names', sa.String(length=100), nullable=False),
    sa.Column('surname', sa.String(length=100), nullable=False),
    sa.Column('id_number', sa.String(length=13), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('mobile_number', sa.String(length=10), nullable=False),
    sa.Column('alternative_number', sa.String(length=10), nullable=True),
    sa.Column('ward', sa.String(length=2), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('municipality', sa.String(length=100), nullable=False),
    sa.Column('house_number', sa.Integer(), nullable=False),
    sa.Column('street_address', sa.String(length=100), nullable=False),
    sa.Column('suburb', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('province', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=4), nullable=False),
    sa.Column('iec_registered', sa.String(length=3), nullable=False),
    sa.Column('pat_no', sa.String(length=100), nullable=True),
    sa.Column('voting_district', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member')
    # ### end Alembic commands ###
